[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aegis-link"
version = "0.0.2"
description = "AQL Link Framework"
authors = [
    { name = "Daniel Beard" }
]
requires-python = ">=3.10"
dependencies = []

[tool.setuptools.packages.find]
include = ["aql_link*"]
